setup:
  path: models/bee-world-500k_v2/
  alias: round5

  continue_training: True
  old_alias: round4
env:
  algorithm: TD3
  gym_name: BeeWorld
  render_mode: rgb_array
  walls: [
        [[5.0, 0.0], [5.0, 5.0]],
        [[2.5, 10.0], [2.5, 6.0]],
    ]
  goal_size: 0.5
  video: True
  agent_location_range: [[0.0, 2.0], [0.0, 10.0]]
  goal_location_range: [[8.0, 10.0], [0.0, 10.0]]
  frame_stack_size: 5

train: 
  timesteps: 500_000
  max_episode_steps: 5000
  policy_kwargs: { net_arch: [300, 200], activation_fn: ReLU }
  learning_rate: 0.0005
  max_no_improvement_evals: 200
  eval_freq: 1000


test:
  prediction_steps: 1000


